[package]
name = "leli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
pulldown-cmark = "0.11.0"
regex = "1.10.5"
diesel = { version = "2.2.0", features = ["sqlite"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
walkdir = "2.5.0"
dirs = "5.0.1"
candle-core = { git = "https://github.com/huggingface/candle.git" }
candle-nn = { git = "https://github.com/huggingface/candle.git" }
candle-transformers = { git = "https://github.com/huggingface/candle.git" }
candle-examples = { git = "https://github.com/huggingface/candle.git" }
anyhow = "1.0.95"
hf-hub = "0.4.1"
tokenizers = { version = "0.19.1", default-features = false }
metal = { version = "0.27.0", features = ["mps"]}
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.7"
serde_json = "1.0.99"
csv = "1.3.1"

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
