[package]
name = "leli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.2" }
candle-examples = { git = "https://github.com/huggingface/candle.git", version = "0.8.2" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.8.2" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.8.2" }
clap = { version = "4.5.10", features = ["derive"] }
csv = "1.3.1"
diesel = { version = "2.2.0", features = ["sqlite"] }
dirs = "5.0.1"
dotenvy = "0.15"
hf-hub = "0.4.1"
metal = { version = "0.27.0", features = ["mps"] }
pulldown-cmark = "0.11.0"
regex = "1.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.99"
serde_yaml = "0.9.34"
tokenizers = { version = "0.19.1", default-features = false }
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.7"
walkdir = "2.5.0"

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
