CREATE TABLE metadata (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    file_path TEXT NOT NULL
);

CREATE TABLE file_content (
    id INTEGER NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (id) REFERENCES metadata(id) ON DELETE CASCADE
);
